/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'appliedJobId' : bigint,
  'name' : string,
  'email' : string,
  'stage' : { 'hired' : null } |
    { 'offer' : null } |
    { 'screening' : null } |
    { 'interview' : null } |
    { 'applied' : null },
  'appliedDate' : Time,
  'notes' : Array<Note>,
  'phone' : string,
}
export interface Conversation {
  'messages' : Array<Message>,
  'candidateId' : bigint,
}
export interface Interview {
  'id' : bigint,
  'status' : { 'scheduled' : null } |
    { 'cancelled' : null } |
    { 'completed' : null },
  'jobId' : bigint,
  'interviewType' : { 'video' : null } |
    { 'phone' : null } |
    { 'onSite' : null },
  'notes' : string,
  'candidateId' : bigint,
  'datetime' : Time,
}
export interface Job {
  'id' : bigint,
  'status' : { 'closed' : null } |
    { 'open' : null } |
    { 'draft' : null },
  'title' : string,
  'postedDate' : Time,
  'description' : string,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'location' : string,
}
export interface Message {
  'text' : string,
  'timestamp' : Time,
  'senderRole' : { 'recruiter' : null } |
    { 'candidate' : null },
}
export interface Note { 'text' : string, 'author' : string, 'timestamp' : Time }
export interface NotificationPreferences {
  'emailAlerts' : boolean,
  'interviewReminders' : boolean,
  'newApplications' : boolean,
}
export interface Settings {
  'notificationPreferences' : NotificationPreferences,
  'teamMembers' : Array<TeamMember>,
}
export interface TeamMember {
  'name' : string,
  'role' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'title' : string,
  'name' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<
    [bigint, { 'recruiter' : null } | { 'candidate' : null }, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelInterview' : ActorMethod<[bigint], undefined>,
  'createCandidate' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      { 'hired' : null } |
        { 'offer' : null } |
        { 'screening' : null } |
        { 'interview' : null } |
        { 'applied' : null },
      Array<Note>,
      Time,
    ],
    bigint
  >,
  'createConversation' : ActorMethod<[bigint], undefined>,
  'createJob' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      { 'closed' : null } |
        { 'open' : null } |
        { 'draft' : null },
      string,
    ],
    bigint
  >,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllConversations' : ActorMethod<[], Array<Conversation>>,
  'getAllInterviews' : ActorMethod<[], Array<Interview>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidate' : ActorMethod<[bigint], [] | [Candidate]>,
  'getConversation' : ActorMethod<[bigint], [] | [Conversation]>,
  'getInterview' : ActorMethod<[bigint], [] | [Interview]>,
  'getInterviewsByCandidate' : ActorMethod<[bigint], Array<Interview>>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getSettings' : ActorMethod<[], [] | [Settings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleInterview' : ActorMethod<
    [
      bigint,
      bigint,
      { 'video' : null } |
        { 'phone' : null } |
        { 'onSite' : null },
      string,
    ],
    bigint
  >,
  'updateCandidate' : ActorMethod<
    [bigint, string, string, string, bigint, Array<Note>],
    undefined
  >,
  'updateCandidateStage' : ActorMethod<
    [
      bigint,
      { 'hired' : null } |
        { 'offer' : null } |
        { 'screening' : null } |
        { 'interview' : null } |
        { 'applied' : null },
    ],
    undefined
  >,
  'updateInterview' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      { 'video' : null } |
        { 'phone' : null } |
        { 'onSite' : null },
      string,
      { 'scheduled' : null } |
        { 'cancelled' : null } |
        { 'completed' : null },
    ],
    undefined
  >,
  'updateJob' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      bigint,
      { 'closed' : null } |
        { 'open' : null } |
        { 'draft' : null },
      string,
    ],
    undefined
  >,
  'updateSettings' : ActorMethod<
    [NotificationPreferences, Array<TeamMember>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];