/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'appliedJobId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'stage' : IDL.Variant({
    'hired' : IDL.Null,
    'offer' : IDL.Null,
    'screening' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
  }),
  'appliedDate' : Time,
  'notes' : IDL.Vec(Note),
  'phone' : IDL.Text,
});
export const Message = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : Time,
  'senderRole' : IDL.Variant({
    'recruiter' : IDL.Null,
    'candidate' : IDL.Null,
  }),
});
export const Conversation = IDL.Record({
  'messages' : IDL.Vec(Message),
  'candidateId' : IDL.Nat,
});
export const Interview = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'jobId' : IDL.Nat,
  'interviewType' : IDL.Variant({
    'video' : IDL.Null,
    'phone' : IDL.Null,
    'onSite' : IDL.Null,
  }),
  'notes' : IDL.Text,
  'candidateId' : IDL.Nat,
  'datetime' : Time,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'draft' : IDL.Null,
  }),
  'title' : IDL.Text,
  'postedDate' : Time,
  'description' : IDL.Text,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const NotificationPreferences = IDL.Record({
  'emailAlerts' : IDL.Bool,
  'interviewReminders' : IDL.Bool,
  'newApplications' : IDL.Bool,
});
export const TeamMember = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const Settings = IDL.Record({
  'notificationPreferences' : NotificationPreferences,
  'teamMembers' : IDL.Vec(TeamMember),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({ 'recruiter' : IDL.Null, 'candidate' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelInterview' : IDL.Func([IDL.Nat], [], []),
  'createCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({
          'hired' : IDL.Null,
          'offer' : IDL.Null,
          'screening' : IDL.Null,
          'interview' : IDL.Null,
          'applied' : IDL.Null,
        }),
        IDL.Vec(Note),
        Time,
      ],
      [IDL.Nat],
      [],
    ),
  'createConversation' : IDL.Func([IDL.Nat], [], []),
  'createJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'closed' : IDL.Null,
          'open' : IDL.Null,
          'draft' : IDL.Null,
        }),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getAllInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidate' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
  'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
  'getInterview' : IDL.Func([IDL.Nat], [IDL.Opt(Interview)], ['query']),
  'getInterviewsByCandidate' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Interview)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleInterview' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'video' : IDL.Null,
          'phone' : IDL.Null,
          'onSite' : IDL.Null,
        }),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateCandidate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(Note)],
      [],
      [],
    ),
  'updateCandidateStage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'hired' : IDL.Null,
          'offer' : IDL.Null,
          'screening' : IDL.Null,
          'interview' : IDL.Null,
          'applied' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateInterview' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'video' : IDL.Null,
          'phone' : IDL.Null,
          'onSite' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({
          'scheduled' : IDL.Null,
          'cancelled' : IDL.Null,
          'completed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'closed' : IDL.Null,
          'open' : IDL.Null,
          'draft' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSettings' : IDL.Func(
      [NotificationPreferences, IDL.Vec(TeamMember)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'appliedJobId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'stage' : IDL.Variant({
      'hired' : IDL.Null,
      'offer' : IDL.Null,
      'screening' : IDL.Null,
      'interview' : IDL.Null,
      'applied' : IDL.Null,
    }),
    'appliedDate' : Time,
    'notes' : IDL.Vec(Note),
    'phone' : IDL.Text,
  });
  const Message = IDL.Record({
    'text' : IDL.Text,
    'timestamp' : Time,
    'senderRole' : IDL.Variant({
      'recruiter' : IDL.Null,
      'candidate' : IDL.Null,
    }),
  });
  const Conversation = IDL.Record({
    'messages' : IDL.Vec(Message),
    'candidateId' : IDL.Nat,
  });
  const Interview = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'scheduled' : IDL.Null,
      'cancelled' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'jobId' : IDL.Nat,
    'interviewType' : IDL.Variant({
      'video' : IDL.Null,
      'phone' : IDL.Null,
      'onSite' : IDL.Null,
    }),
    'notes' : IDL.Text,
    'candidateId' : IDL.Nat,
    'datetime' : Time,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'open' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'title' : IDL.Text,
    'postedDate' : Time,
    'description' : IDL.Text,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const NotificationPreferences = IDL.Record({
    'emailAlerts' : IDL.Bool,
    'interviewReminders' : IDL.Bool,
    'newApplications' : IDL.Bool,
  });
  const TeamMember = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const Settings = IDL.Record({
    'notificationPreferences' : NotificationPreferences,
    'teamMembers' : IDL.Vec(TeamMember),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'recruiter' : IDL.Null, 'candidate' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelInterview' : IDL.Func([IDL.Nat], [], []),
    'createCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({
            'hired' : IDL.Null,
            'offer' : IDL.Null,
            'screening' : IDL.Null,
            'interview' : IDL.Null,
            'applied' : IDL.Null,
          }),
          IDL.Vec(Note),
          Time,
        ],
        [IDL.Nat],
        [],
      ),
    'createConversation' : IDL.Func([IDL.Nat], [], []),
    'createJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'closed' : IDL.Null,
            'open' : IDL.Null,
            'draft' : IDL.Null,
          }),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getAllInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidate' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
    'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
    'getInterview' : IDL.Func([IDL.Nat], [IDL.Opt(Interview)], ['query']),
    'getInterviewsByCandidate' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Interview)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleInterview' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'video' : IDL.Null,
            'phone' : IDL.Null,
            'onSite' : IDL.Null,
          }),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateCandidate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(Note)],
        [],
        [],
      ),
    'updateCandidateStage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'hired' : IDL.Null,
            'offer' : IDL.Null,
            'screening' : IDL.Null,
            'interview' : IDL.Null,
            'applied' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateInterview' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'video' : IDL.Null,
            'phone' : IDL.Null,
            'onSite' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'scheduled' : IDL.Null,
            'cancelled' : IDL.Null,
            'completed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'closed' : IDL.Null,
            'open' : IDL.Null,
            'draft' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSettings' : IDL.Func(
        [NotificationPreferences, IDL.Vec(TeamMember)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };