/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settings {
    notificationPreferences: NotificationPreferences;
    teamMembers: Array<TeamMember>;
}
export interface NotificationPreferences {
    emailAlerts: boolean;
    interviewReminders: boolean;
    newApplications: boolean;
}
export type Time = bigint;
export interface Job {
    id: bigint;
    status: Variant_closed_open_draft;
    title: string;
    postedDate: Time;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
}
export interface Interview {
    id: bigint;
    status: Variant_scheduled_cancelled_completed;
    jobId: bigint;
    interviewType: Variant_video_phone_onSite;
    notes: string;
    candidateId: bigint;
    datetime: Time;
}
export interface Candidate {
    id: bigint;
    appliedJobId: bigint;
    name: string;
    email: string;
    stage: Variant_hired_offer_screening_interview_applied;
    appliedDate: Time;
    notes: Array<Note>;
    phone: string;
}
export interface TeamMember {
    name: string;
    role: string;
    email: string;
    avatarUrl: string;
}
export interface Message {
    text: string;
    timestamp: Time;
    senderRole: Variant_recruiter_candidate;
}
export interface Conversation {
    messages: Array<Message>;
    candidateId: bigint;
}
export interface UserProfile {
    bio: string;
    title: string;
    name: string;
    email: string;
    avatarUrl: string;
}
export interface Note {
    text: string;
    author: string;
    timestamp: Time;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_closed_open_draft {
    closed = "closed",
    open = "open",
    draft = "draft"
}
export enum Variant_hired_offer_screening_interview_applied {
    hired = "hired",
    offer = "offer",
    screening = "screening",
    interview = "interview",
    applied = "applied"
}
export enum Variant_recruiter_candidate {
    recruiter = "recruiter",
    candidate = "candidate"
}
export enum Variant_scheduled_cancelled_completed {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum Variant_video_phone_onSite {
    video = "video",
    phone = "phone",
    onSite = "onSite"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMessage(candidateId: bigint, senderRole: Variant_recruiter_candidate, text: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelInterview(id: bigint): Promise<void>;
    createCandidate(name: string, email: string, phone: string, appliedJobId: bigint, stage: Variant_hired_offer_screening_interview_applied, notes: Array<Note>, appliedDate: Time): Promise<bigint>;
    createConversation(candidateId: bigint): Promise<void>;
    createJob(title: string, location: string, salaryMin: bigint, salaryMax: bigint, status: Variant_closed_open_draft, description: string): Promise<bigint>;
    deleteCandidate(id: bigint): Promise<void>;
    deleteJob(id: bigint): Promise<void>;
    getAllCandidates(): Promise<Array<Candidate>>;
    getAllConversations(): Promise<Array<Conversation>>;
    getAllInterviews(): Promise<Array<Interview>>;
    getAllJobs(): Promise<Array<Job>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidate(id: bigint): Promise<Candidate | null>;
    getConversation(candidateId: bigint): Promise<Conversation | null>;
    getInterview(id: bigint): Promise<Interview | null>;
    getInterviewsByCandidate(candidateId: bigint): Promise<Array<Interview>>;
    getJob(id: bigint): Promise<Job | null>;
    getSettings(): Promise<Settings | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleInterview(candidateId: bigint, jobId: bigint, interviewType: Variant_video_phone_onSite, notes: string): Promise<bigint>;
    updateCandidate(id: bigint, name: string, email: string, phone: string, appliedJobId: bigint, notes: Array<Note>): Promise<void>;
    updateCandidateStage(id: bigint, newStage: Variant_hired_offer_screening_interview_applied): Promise<void>;
    updateInterview(id: bigint, candidateId: bigint, jobId: bigint, interviewType: Variant_video_phone_onSite, notes: string, status: Variant_scheduled_cancelled_completed): Promise<void>;
    updateJob(id: bigint, title: string, location: string, salaryMin: bigint, salaryMax: bigint, status: Variant_closed_open_draft, description: string): Promise<void>;
    updateSettings(notificationPreferences: NotificationPreferences, teamMembers: Array<TeamMember>): Promise<void>;
}
import type { Candidate as _Candidate, Conversation as _Conversation, Interview as _Interview, Job as _Job, Message as _Message, Note as _Note, Settings as _Settings, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMessage(arg0: bigint, arg1: Variant_recruiter_candidate, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelInterview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelInterview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelInterview(arg0);
            return result;
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Variant_hired_offer_screening_interview_applied, arg5: Array<Note>, arg6: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createConversation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0);
            return result;
        }
    }
    async createJob(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: Variant_closed_open_draft, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, arg1, arg2, arg3, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, arg1, arg2, arg3, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async deleteCandidate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAllCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCandidates();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCandidates();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversations();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversations();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInterviews(): Promise<Array<Interview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInterviews();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInterviews();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidate(arg0: bigint): Promise<Candidate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidate(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidate(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: bigint): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterview(arg0: bigint): Promise<Interview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterview(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterview(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterviewsByCandidate(arg0: bigint): Promise<Array<Interview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewsByCandidate(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewsByCandidate(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async scheduleInterview(arg0: bigint, arg1: bigint, arg2: Variant_video_phone_onSite, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleInterview(arg0, arg1, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleInterview(arg0, arg1, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateCandidate(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Array<Note>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCandidateStage(arg0: bigint, arg1: Variant_hired_offer_screening_interview_applied): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidateStage(arg0, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidateStage(arg0, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateInterview(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Variant_video_phone_onSite, arg4: string, arg5: Variant_scheduled_cancelled_completed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInterview(arg0, arg1, arg2, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInterview(arg0, arg1, arg2, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_variant_n35(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: Variant_closed_open_draft, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateSettings(arg0: NotificationPreferences, arg1: Array<TeamMember>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Candidate_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candidate): Candidate {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Interview_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interview): Interview {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Candidate]): Candidate | null {
    return value.length === 0 ? null : from_candid_Candidate_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : from_candid_Conversation_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Interview]): Interview | null {
    return value.length === 0 ? null : from_candid_Interview_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Settings]): Settings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<_Message>;
    candidateId: bigint;
}): {
    messages: Array<Message>;
    candidateId: bigint;
} {
    return {
        messages: from_candid_vec_n13(_uploadFile, _downloadFile, value.messages),
        candidateId: value.candidateId
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    timestamp: _Time;
    senderRole: {
        recruiter: null;
    } | {
        candidate: null;
    };
}): {
    text: string;
    timestamp: Time;
    senderRole: Variant_recruiter_candidate;
} {
    return {
        text: value.text,
        timestamp: value.timestamp,
        senderRole: from_candid_variant_n16(_uploadFile, _downloadFile, value.senderRole)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        scheduled: null;
    } | {
        cancelled: null;
    } | {
        completed: null;
    };
    jobId: bigint;
    interviewType: {
        video: null;
    } | {
        phone: null;
    } | {
        onSite: null;
    };
    notes: string;
    candidateId: bigint;
    datetime: _Time;
}): {
    id: bigint;
    status: Variant_scheduled_cancelled_completed;
    jobId: bigint;
    interviewType: Variant_video_phone_onSite;
    notes: string;
    candidateId: bigint;
    datetime: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        jobId: value.jobId,
        interviewType: from_candid_variant_n21(_uploadFile, _downloadFile, value.interviewType),
        notes: value.notes,
        candidateId: value.candidateId,
        datetime: value.datetime
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        closed: null;
    } | {
        open: null;
    } | {
        draft: null;
    };
    title: string;
    postedDate: _Time;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
}): {
    id: bigint;
    status: Variant_closed_open_draft;
    title: string;
    postedDate: Time;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        postedDate: value.postedDate,
        description: value.description,
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        location: value.location
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    appliedJobId: bigint;
    name: string;
    email: string;
    stage: {
        hired: null;
    } | {
        offer: null;
    } | {
        screening: null;
    } | {
        interview: null;
    } | {
        applied: null;
    };
    appliedDate: _Time;
    notes: Array<_Note>;
    phone: string;
}): {
    id: bigint;
    appliedJobId: bigint;
    name: string;
    email: string;
    stage: Variant_hired_offer_screening_interview_applied;
    appliedDate: Time;
    notes: Array<Note>;
    phone: string;
} {
    return {
        id: value.id,
        appliedJobId: value.appliedJobId,
        name: value.name,
        email: value.email,
        stage: from_candid_variant_n9(_uploadFile, _downloadFile, value.stage),
        appliedDate: value.appliedDate,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recruiter: null;
} | {
    candidate: null;
}): Variant_recruiter_candidate {
    return "recruiter" in value ? Variant_recruiter_candidate.recruiter : "candidate" in value ? Variant_recruiter_candidate.candidate : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): Variant_scheduled_cancelled_completed {
    return "scheduled" in value ? Variant_scheduled_cancelled_completed.scheduled : "cancelled" in value ? Variant_scheduled_cancelled_completed.cancelled : "completed" in value ? Variant_scheduled_cancelled_completed.completed : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    phone: null;
} | {
    onSite: null;
}): Variant_video_phone_onSite {
    return "video" in value ? Variant_video_phone_onSite.video : "phone" in value ? Variant_video_phone_onSite.phone : "onSite" in value ? Variant_video_phone_onSite.onSite : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
}): Variant_closed_open_draft {
    return "closed" in value ? Variant_closed_open_draft.closed : "open" in value ? Variant_closed_open_draft.open : "draft" in value ? Variant_closed_open_draft.draft : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    applied: null;
}): Variant_hired_offer_screening_interview_applied {
    return "hired" in value ? Variant_hired_offer_screening_interview_applied.hired : "offer" in value ? Variant_hired_offer_screening_interview_applied.offer : "screening" in value ? Variant_hired_offer_screening_interview_applied.screening : "interview" in value ? Variant_hired_offer_screening_interview_applied.interview : "applied" in value ? Variant_hired_offer_screening_interview_applied.applied : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interview>): Array<Interview> {
    return value.map((x)=>from_candid_Interview_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candidate>): Array<Candidate> {
    return value.map((x)=>from_candid_Candidate_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_recruiter_candidate): {
    recruiter: null;
} | {
    candidate: null;
} {
    return value == Variant_recruiter_candidate.recruiter ? {
        recruiter: null
    } : value == Variant_recruiter_candidate.candidate ? {
        candidate: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_video_phone_onSite): {
    video: null;
} | {
    phone: null;
} | {
    onSite: null;
} {
    return value == Variant_video_phone_onSite.video ? {
        video: null
    } : value == Variant_video_phone_onSite.phone ? {
        phone: null
    } : value == Variant_video_phone_onSite.onSite ? {
        onSite: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_scheduled_cancelled_completed): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == Variant_scheduled_cancelled_completed.scheduled ? {
        scheduled: null
    } : value == Variant_scheduled_cancelled_completed.cancelled ? {
        cancelled: null
    } : value == Variant_scheduled_cancelled_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_hired_offer_screening_interview_applied): {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    applied: null;
} {
    return value == Variant_hired_offer_screening_interview_applied.hired ? {
        hired: null
    } : value == Variant_hired_offer_screening_interview_applied.offer ? {
        offer: null
    } : value == Variant_hired_offer_screening_interview_applied.screening ? {
        screening: null
    } : value == Variant_hired_offer_screening_interview_applied.interview ? {
        interview: null
    } : value == Variant_hired_offer_screening_interview_applied.applied ? {
        applied: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_open_draft): {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
} {
    return value == Variant_closed_open_draft.closed ? {
        closed: null
    } : value == Variant_closed_open_draft.open ? {
        open: null
    } : value == Variant_closed_open_draft.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
